version: '3.5'

volumes:
    hadoop_datanode:
        name: hadoop_datanode
    hadoop_datanode_logs:
        name: hadoop_datanode_logs

services:
    datanode:
        image: malkab/hadoop:3.3.6
        hostname: kepler
        container_name: hadoop_datanode
        network_mode: host

        environment:
            HADOOP_HEAPSIZE_MAX: 5g
            HDFS_DATANODE_OPTS: "-XX:+UseParallelGC -Xmx4g"
            HDFS_SITE_DFS_NAMENODE_RPC_ADDRESS: helios:9022
            HDFS_SITE_DFS_DATANODE_HTTP_ADDRESS: 0.0.0.0:8036

        volumes:
            - hadoop_datanode:/data_datanode
            - hadoop_datanode_logs:/hadoop/logs

        command: -c "/run_datanode.sh"
