version: '3.5'

volumes:
    hadoop_datanode:
        name: hadoop_datanode
    hadoop_datanode_logs:
        name: hadoop_datanode_logs

services:
    datanode:
        image: malkab/hadoop:3.3.6
        # hostname is mandatory
        hostname: kepler
        container_name: hadoop_datanode
        # host network mode is mandatory
        network_mode: host

        environment:
            # Mandatory, where the namenode is available.
            CORE_SITE_FS_DEFAULTFS: helios:9000
            HDFS_SITE_DFS_NAMENODE_RPC_ADDRESS: helios:9000

            # Configuration, not mandatory.
            HADOOP_HEAPSIZE_MAX: 5g
            HADOOP_ROOT_LOGGER: INFO,DRFA
            HDFS_DATANODE_OPTS: "-XX:+UseParallelGC -Xmx4g"

            # The Datanode dashboard is available here. Change only in case of
            # port conflict.
            HDFS_SITE_DFS_DATANODE_HTTP_ADDRESS: 0.0.0.0:8030
            # Datanode address. Change only in case of port conflict.
            HDFS_SITE_DFS_DATANODE_ADDRESS: 0.0.0.0:9879
            # This is the interprocess communication address. Change only in
            # case of port conflict.
            HDFS_SITE_DFS_DATANODE_IPC_ADDRESS: 0.0.0.0:9999

        volumes:
            - hadoop_datanode:/data_datanode
            - hadoop_datanode_logs:/hadoop/logs

        command: -c "/run_datanode.sh"
